# Generated by Django 4.2 on 2025-11-06 23:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('water_app', '0003_waterintakemodel_delete_waterquantitymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterintakemodel',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
