# Generated by Django 4.2 on 2025-11-07 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_app', '0004_alter_waterintakemodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterintakemodel',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
